# Generated by Django 6.1 on 2026-08-25 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nomi')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Kod')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Xorijiy til',
                'verbose_name_plural': 'Xorijiy tillar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nomi')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Mutaxassislik',
                'verbose_name_plural': 'Mutaxassisliklar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Savol')),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Savol rasmi')),
                ('category', models.CharField(choices=[('speciality', 'Mutaxassislik'), ('pedagogy', 'Pedagogika'), ('it', 'IT'), ('foreign_language', 'Xorijiy til')], max_length=30, verbose_name='Kategoriya')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('foreign_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='questions.foreignlanguage', verbose_name='Xorijiy til')),
                ('speciality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='questions.speciality', verbose_name='Mutaxassislik')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Javob matni')),
                ('image', models.ImageField(blank=True, null=True, upload_to='choices/', verbose_name='Javob rasmi')),
                ('is_correct', models.BooleanField(default=False, verbose_name='To‘g‘ri javob')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='questions.question')),
            ],
            options={
                'verbose_name': 'Javob varianti',
                'verbose_name_plural': 'Javob variantlari',
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['category', 'is_active'], name='questions_q_categor_aff032_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['category', 'speciality', 'is_active'], name='questions_q_categor_fb246b_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['category', 'foreign_language', 'is_active'], name='questions_q_categor_e5b104_idx'),
        ),
    ]
