# Generated by Django 6.1 on 2026-08-25 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Test nomi')),
                ('duration_minutes', models.PositiveIntegerField(default=90, verbose_name='Davomiyligi (daqiqa)')),
                ('speciality_count', models.PositiveIntegerField(default=30, verbose_name='Mutaxassislik savollari')),
                ('pedagogy_count', models.PositiveIntegerField(default=10, verbose_name='Pedagogika savollari')),
                ('it_count', models.PositiveIntegerField(default=5, verbose_name='IT savollari')),
                ('language_count', models.PositiveIntegerField(default=5, verbose_name='Xorijiy til savollari')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Testlar',
            },
        ),
        migrations.CreateModel(
            name='AttemptQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('selected_choice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.choice')),
                ('attempt_question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='exams.attemptquestion')),
            ],
            options={
                'verbose_name': 'Tanlangan javob',
                'verbose_name_plural': 'Tanlangan javoblar',
            },
        ),
        migrations.CreateModel(
            name='TestAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_from', models.DateTimeField(blank=True, null=True, verbose_name='Boshlanish vaqti')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi muddat')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='exams.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Test biriktirish',
                'verbose_name_plural': 'Test biriktirishlar',
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'Jarayonda'), ('finished', 'Yakunlangan'), ('expired', 'Vaqt tugagan')], default='in_progress', max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attempt', to='exams.testassignment')),
                ('foreign_language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.foreignlanguage')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.speciality')),
            ],
            options={
                'verbose_name': 'Test natijasi',
                'verbose_name_plural': 'Test natijalari',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='attemptquestion',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_questions', to='exams.testattempt'),
        ),
        migrations.CreateModel(
            name='AttemptChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.choice')),
                ('attempt_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_choices', to='exams.attemptquestion')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('attempt_question', 'choice'), name='unique_choice_per_attempt_question'), models.UniqueConstraint(fields=('attempt_question', 'order'), name='unique_choice_order_per_attempt_question')],
            },
        ),
        migrations.AddConstraint(
            model_name='testassignment',
            constraint=models.UniqueConstraint(fields=('test', 'user'), name='unique_test_assignment_per_user'),
        ),
        migrations.AddConstraint(
            model_name='attemptquestion',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_question_per_attempt'),
        ),
        migrations.AddConstraint(
            model_name='attemptquestion',
            constraint=models.UniqueConstraint(fields=('attempt', 'order'), name='unique_question_order_per_attempt'),
        ),
    ]
