# Generated by Django 6.1 on 2026-08-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testassignment',
            name='status',
            field=models.CharField(choices=[('p', 'P'), ('f', 'f'), ('d', 'd')], default='d', max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, verbose_name='Davomiyligi (daqiqa)'),
        ),
    ]
